######################################################################
# Automatically generated by qmake (2.01a) ? 6? 29 12:17:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bomb.h compoint.h mainwidget.h player.h playwidget.h wall.h
SOURCES += bomb.cpp main.cpp mainwidget.cpp player.cpp playwidget.cpp wall.cpp
